"""empty message

Revision ID: 86cd1d7b36b1
Revises: 8f00c061dac1
Create Date: 2018-11-16 19:14:02.472301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86cd1d7b36b1'
down_revision = '8f00c061dac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'banana')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('banana', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
